# Generated by Django 6.0.3 on 2026-04-11 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_org_signature_document_org_signed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
        migrations.RemoveField(
            model_name='document',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='document',
            name='signed_at',
        ),
        migrations.AddField(
            model_name='template',
            name='template_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signatures', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
            ],
            options={
                'unique_together': {('document', 'client')},
            },
        ),
    ]
