# Generated by Django 6.0.3 on 2026-05-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_client_remove_document_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='manager_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
