# Generated by Django 6.0.3 on 2026-05-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_client_fields_document_manager_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='OTPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_sessions', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
