# Generated by Django 6.0.1 on 2026-01-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('ORGANIZATION', 'Organization'), ('CLIENT', 'Client')], default='CLIENT', help_text='User role for permission handling', max_length=20),
        ),
    ]
